// Code generated by gogenconf. DO NOT EDIT.

package binding

import (
	"context"
	"fmt"
	gogenconf "github.com/arran4/gogenconf"
	"strings"
)
import runtimeconfig "github.com/arran4/gogenconf/examples/codegen/appconfig"

var _ = strings.Join
var _ = fmt.Errorf

// Defaults returns concrete static defaults and optional legacy environment overrides.
func Defaults(lookup gogenconf.LookupEnv) runtimeconfig.Config {
	var c runtimeconfig.Config
	c.Service.Endpoint = "https://example.test"
	return c
}

// Resolve constructs ordinary Go fields; provider policy alone defers resolution.
func Resolve(ctx context.Context, d *gogenconf.Document, r *gogenconf.Registry, lookup gogenconf.LookupEnv) (runtimeconfig.Config, error) {
	var c runtimeconfig.Config
	if d == nil {
		return c, fmt.Errorf("nil document")
	}
	if d.Version > 1 {
		return c, fmt.Errorf("unsupported future configuration version")
	}
	{
		e := gogenconf.BindingValue(d, "service", "endpoint", gogenconf.Literal{Value: "https://example.test"}, "", false, lookup)
		if e != nil {
			value, err := gogenconf.ResolveField[string](ctx, r, e, "service.endpoint", false)
			if err != nil {
				return runtimeconfig.Config{}, err
			}
			c.Service.Endpoint = value
		}
	}
	{
		e := gogenconf.BindingValue(d, "service", "credential", nil, "", false, lookup)
		if e == nil {
			return runtimeconfig.Config{}, fmt.Errorf("missing required field service.credential")
		}
		if e != nil {
			value, err := gogenconf.ResolveField[[]byte](ctx, r, e, "service.credential", true)
			if err != nil {
				return runtimeconfig.Config{}, err
			}
			c.Service.Credential = value
		}
	}
	return c, nil
}
