package codegen_test

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arran4/gogenconf/codegen"
)

func TestRuntimeDeterministicGeneration(t *testing.T) {
	opts := codegen.RuntimeOptions{
		Package: "runtimefixture",
	}

	first, err := codegen.GenerateRuntime(opts)
	if err != nil {
		t.Fatalf("first GenerateRuntime failed: %v", err)
	}

	second, err := codegen.GenerateRuntime(opts)
	if err != nil {
		t.Fatalf("second GenerateRuntime failed: %v", err)
	}

	if len(first) != len(second) {
		t.Fatalf("file count mismatch: %d vs %d", len(first), len(second))
	}

	for i := range first {
		if first[i].Name != second[i].Name {
			t.Fatalf("file %d name mismatch: %s vs %s", i, first[i].Name, second[i].Name)
		}
		if !bytes.Equal(first[i].Content, second[i].Content) {
			t.Fatalf("file %s content is nondeterministic", first[i].Name)
		}
	}
}

func TestRuntimeFixtureMatchesCheckedIn(t *testing.T) {
	opts := codegen.RuntimeOptions{
		Package: "runtimefixture",
	}

	files, err := codegen.GenerateRuntime(opts)
	if err != nil {
		t.Fatalf("GenerateRuntime failed: %v", err)
	}

	expectedFiles := []string{
		"config_document_generated.go",
		"config_expr_generated.go",
		"config_parse_generated.go",
		"config_format_generated.go",
	}

	if len(files) != len(expectedFiles) {
		t.Fatalf("expected %d files, got %d", len(expectedFiles), len(files))
	}

	for i, wantName := range expectedFiles {
		if files[i].Name != wantName {
			t.Fatalf("file %d: expected name %q, got %q", i, wantName, files[i].Name)
		}

		diskPath := filepath.Join("internal/runtimefixture", wantName)
		wantBytes, err := os.ReadFile(diskPath)
		if err != nil {
			t.Fatalf("failed reading %s: %v", diskPath, err)
		}

		if !bytes.Equal(files[i].Content, wantBytes) {
			t.Fatalf("file %s on disk is stale or does not match generator output", wantName)
		}
	}
}

func TestRuntimeNoGogenconfImportsAndValidHeaders(t *testing.T) {
	opts := codegen.RuntimeOptions{
		Package: "myconfig",
	}

	files, err := codegen.GenerateRuntime(opts)
	if err != nil {
		t.Fatalf("GenerateRuntime failed: %v", err)
	}

	for _, f := range files {
		content := string(f.Content)

		if strings.Contains(content, "github.com/arran4/gogenconf") {
			t.Errorf("file %s illegally imports github.com/arran4/gogenconf", f.Name)
		}

		if !strings.HasPrefix(content, "// Code generated by gogenconf. DO NOT EDIT.\n") {
			t.Errorf("file %s missing canonical generated header", f.Name)
		}

		if !strings.Contains(content, "package myconfig") {
			t.Errorf("file %s missing expected package declaration", f.Name)
		}
	}
}

func TestRuntimeCapabilitiesAndPrerequisites(t *testing.T) {
	// Only Expr requested: should only emit expr
	exprOnly, err := codegen.GenerateRuntime(codegen.RuntimeOptions{
		Package:      "onlyexpr",
		Capabilities: []codegen.Capability{codegen.CapabilityExpr},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(exprOnly) != 1 || exprOnly[0].Name != "config_expr_generated.go" {
		t.Fatalf("expected only expr file, got %v", exprOnly)
	}

	// Document requested: must auto-include Expr because Document AST references Expr
	docOnly, err := codegen.GenerateRuntime(codegen.RuntimeOptions{
		Package:      "docandexpr",
		Capabilities: []codegen.Capability{codegen.CapabilityDocument},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(docOnly) != 2 {
		t.Fatalf("expected document and expr files, got %d files", len(docOnly))
	}
	if docOnly.File("config_document_generated.go") == nil || docOnly.File("config_expr_generated.go") == nil {
		t.Fatalf("missing document or expr in %v", docOnly)
	}

	// Parser requested: must auto-include Document and Expr
	parseOnly, err := codegen.GenerateRuntime(codegen.RuntimeOptions{
		Package:      "parseronly",
		Capabilities: []codegen.Capability{codegen.CapabilityParser},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(parseOnly) != 3 {
		t.Fatalf("expected parse, document, and expr files, got %d files", len(parseOnly))
	}
	if parseOnly.File("config_format_generated.go") != nil {
		t.Fatal("unexpected formatter in parseOnly plan")
	}

	// Custom prefix
	customPrefix, err := codegen.GenerateRuntime(codegen.RuntimeOptions{
		Package:    "custom",
		FilePrefix: "myapp_",
	})
	if err != nil {
		t.Fatal(err)
	}
	if customPrefix.File("myapp_document_generated.go") == nil {
		t.Fatalf("custom prefix not respected in %v", customPrefix)
	}

	// Invalid package name
	if _, err := codegen.GenerateRuntime(codegen.RuntimeOptions{Package: "123bad"}); err == nil {
		t.Fatal("accepted invalid package name")
	}
	if _, err := codegen.GenerateRuntime(codegen.RuntimeOptions{Package: "_"}); err == nil {
		t.Fatal("accepted blank package name")
	}

	// Unknown capability
	if _, err := codegen.GenerateRuntime(codegen.RuntimeOptions{
		Package:      "badcap",
		Capabilities: []codegen.Capability{"telepathy"},
	}); err == nil {
		t.Fatal("accepted unknown capability")
	}
}

func TestRuntimeWriteToDir(t *testing.T) {
	dir := t.TempDir()
	outDir := filepath.Join(dir, "sub", "config")

	files, err := codegen.GenerateRuntime(codegen.RuntimeOptions{
		Package: "config",
	})
	if err != nil {
		t.Fatal(err)
	}

	if err := files.WriteToDir(outDir); err != nil {
		t.Fatalf("WriteToDir failed: %v", err)
	}

	for _, f := range files {
		path := filepath.Join(outDir, f.Name)
		b, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading written file %s: %v", f.Name, err)
		}
		if !bytes.Equal(b, f.Content) {
			t.Fatalf("content mismatch for %s", f.Name)
		}
	}
}

func TestTemplatesMatchCanonicalSource(t *testing.T) {
	// Verify that the templates in codegen match the canonical implementation
	// by rendering them with package gogenconf and comparing AST declarations
	// with the root document.go, expr.go, and format.go.
	files, err := codegen.GenerateRuntime(codegen.RuntimeOptions{
		Package: "gogenconf",
	})
	if err != nil {
		t.Fatal(err)
	}

	fset := token.NewFileSet()

	// Parse all generated runtime files into a package AST
	genAsts := make(map[string]bool)
	for _, f := range files {
		parsed, err := parser.ParseFile(fset, f.Name, f.Content, 0)
		if err != nil {
			t.Fatalf("failed parsing generated file %s: %v", f.Name, err)
		}
		for _, decl := range parsed.Decls {
			// Skip imports
			if genDecl, ok := decl.(*ast.GenDecl); ok && genDecl.Tok == token.IMPORT {
				continue
			}
			genAsts[declString(fset, decl)] = true
		}
	}

	// Check canonical root files
	rootFiles := []string{"../document.go", "../expr.go", "../format.go"}
	for _, rfPath := range rootFiles {
		content, err := os.ReadFile(rfPath)
		if err != nil {
			t.Fatalf("failed reading %s: %v", rfPath, err)
		}
		parsed, err := parser.ParseFile(fset, rfPath, content, 0)
		if err != nil {
			t.Fatalf("failed parsing canonical file %s: %v", rfPath, err)
		}
		for _, decl := range parsed.Decls {
			// Skip imports
			if genDecl, ok := decl.(*ast.GenDecl); ok && genDecl.Tok == token.IMPORT {
				continue
			}
			sig := declString(fset, decl)
			if !genAsts[sig] {
				t.Errorf("canonical declaration %q from %s not found in generated runtime templates", sig, rfPath)
			}
		}
	}
}

func declString(fset *token.FileSet, decl ast.Decl) string {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, decl); err != nil {
		return fmt.Sprintf("%v", decl)
	}
	return buf.String()
}
