// Code generated by gogenconf. DO NOT EDIT.

package runtimefixture

import (
	"fmt"
	"strconv"
	"strings"
	"unicode"
)

// Format never resolves values and retains the position of every root item,
// including comments between sections and trailing comments.
func Format(d *Document) string {
	var b strings.Builder
	var write func([]Item, string)
	write = func(items []Item, indent string) {
		for _, item := range items {
			switch v := item.(type) {
			case Version:
				if d.HasVersion {
					fmt.Fprintf(&b, "config_version %d\n", d.Version)
				}
			case *Section:
				fmt.Fprintf(&b, "section %s\n", v.Name)
				write(v.Items, "    ")
				b.WriteString("end\n")
			case Entry:
				if v.Value == nil {
					fmt.Fprintf(&b, "%s%s\n", indent, v.Key)
				} else {
					fmt.Fprintf(&b, "%s%s %s\n", indent, v.Key, FormatExpr(v.Value))
				}
			case Comment:
				marker := "#"
				if v.Kind == DocumentationComment {
					marker = "##"
				}
				fmt.Fprintf(&b, "%s%s", indent, marker)
				if v.Text != "" {
					if v.Kind == UserComment && (!d.HasVersion || d.Version == 0) && strings.HasPrefix(v.Text, "#") {
						// Retain legacy heading spelling. In v1 the separating
						// space is mandatory to retain user ownership on reload.
						b.WriteString(v.Text)
					} else {
						b.WriteString(" " + v.Text)
					}
				}
				b.WriteByte('\n')
			case Blank:
				b.WriteByte('\n')
			case Raw:
				fmt.Fprintf(&b, "%s%s\n", indent, v.Text)
			}
		}
	}
	version, sections := false, false
	for _, i := range d.Items {
		switch i.(type) {
		case Version:
			version = true
		case *Section:
			sections = true
		}
	}
	if d.HasVersion && !version {
		fmt.Fprintf(&b, "config_version %d\n", d.Version)
	}
	write(d.Items, "")
	if !sections {
		for i, s := range d.Sections {
			if i > 0 {
				b.WriteByte('\n')
			}
			write([]Item{s}, "")
		}
	}
	return b.String()
}

// FormatExpr renders an expression canonically without resolving it.
func FormatExpr(e Expr) string {
	switch e := e.(type) {
	case Literal:
		if bareLiteral(e.Value) {
			return e.Value
		}
		return strconv.Quote(e.Value)
	case *Literal:
		return FormatExpr(*e)
	case Call:
		args := make([]string, len(e.Args))
		for i, a := range e.Args {
			args[i] = FormatExpr(a)
		}
		return e.Name + "(" + strings.Join(args, ", ") + ")"
	case *Call:
		return FormatExpr(*e)
	default:
		return ""
	}
}

func bareLiteral(v string) bool {
	if v == "" {
		return false
	}
	for _, r := range v {
		if unicode.IsSpace(r) || r == '(' || r == ')' || r == ',' || r == '"' || r == '\\' {
			return false
		}
	}
	return true
}
