// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"
)

var _ Cmd = (*Expr)(nil)

type Expr struct {
	*RootCmd
	Flags         *flag.FlagSet
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Expr) error
}

type UsageDataExpr struct {
	*Expr
	Recursive bool
}

func (c *Expr) Usage() {
	err := executeUsage(os.Stderr, "expr_usage.txt", UsageDataExpr{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Expr) UsageRecursive() {
	err := executeUsage(os.Stderr, "expr_usage.txt", UsageDataExpr{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Expr) Execute(args []string) (err error) {
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	c.Usage()

	return nil
}

func (c *RootCmd) NewExpr() *Expr {
	set := flag.NewFlagSet("expr", flag.ContinueOnError)
	v := &Expr{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}
	set.Usage = v.Usage

	{
		subCmd := NewLazyCommand(func() Cmd { return v.NewExprFormat() })
		v.SubCommands["format"] = subCmd

	}

	{
		subCmd := NewLazyCommand(func() Cmd { return v.NewExprValidate() })
		v.SubCommands["validate"] = subCmd

	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
