// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestFormat_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewFormat()

	called := false
	cmd.CommandAction = func(c *Format) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--write")
	args = append(args, "--check")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.file != "test" {
		t.Errorf("Expected file to be 'test', got '%v'", cmd.file)
	}
	if cmd.write != true {
		t.Errorf("Expected write to be true, got '%v'", cmd.write)
	}
	if cmd.check != true {
		t.Errorf("Expected check to be true, got '%v'", cmd.check)
	}
}

func TestFormat_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewFormat()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
