// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestRoot_Execute(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	called := false
	cmd.CommandAction = func(c *RootCmd) error {
		called = true
		return nil
	}

	args := []string{}

	err = cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

}

func TestRoot_ExecuteHelpAndUnknownFlags(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
