// Code generated by address-configgen. DO NOT EDIT.

package testfixture

import (
	"context"
	"fmt"
	configmodel "github.com/arran4/address/internal/configmodel"
	"strings"
)

var _ = strings.Join
var _ = fmt.Errorf

type Config struct {
	Service ServiceConfig
}
type ServiceConfig struct {
	Label   string
	Key     []byte
	Content configmodel.Provider[[]byte]
}

// Defaults returns concrete static defaults and optional legacy environment overrides.
func Defaults(lookup configmodel.LookupEnv) Config {
	var c Config
	c.Service.Label = "default"
	if lookup != nil {
		if v, ok := lookup("FIXTURE_LABEL"); ok {
			c.Service.Label = v
		}
	}
	return c
}

// Resolve constructs ordinary Go fields; provider policy alone defers resolution.
func Resolve(ctx context.Context, d *configmodel.Document, r *configmodel.Registry, lookup configmodel.LookupEnv) (Config, error) {
	var c Config
	if d == nil {
		return c, fmt.Errorf("nil document")
	}
	if d.Version > 2 {
		return c, fmt.Errorf("unsupported future configuration version")
	}
	{
		e := configmodel.BindingValue(d, "service", "label", configmodel.Literal{Value: "default"}, "FIXTURE_LABEL", false, lookup)
		if e == nil {
			return Config{}, fmt.Errorf("missing required field service.label")
		}
		if e != nil {
			value, err := configmodel.ResolveField[string](ctx, r, e, "service.label", false)
			if err != nil {
				return Config{}, err
			}
			c.Service.Label = value
		}
	}
	{
		e := configmodel.BindingValue(d, "service", "key", nil, "", false, lookup)
		if e == nil {
			return Config{}, fmt.Errorf("missing required field service.key")
		}
		if e != nil {
			value, err := configmodel.ResolveField[[]byte](ctx, r, e, "service.key", true)
			if err != nil {
				return Config{}, err
			}
			c.Service.Key = value
		}
	}
	{
		e := configmodel.BindingValue(d, "service", "content", nil, "", false, lookup)
		if e == nil {
			return Config{}, fmt.Errorf("missing required field service.content")
		}
		if e != nil {
			c.Service.Content = configmodel.FieldProvider[[]byte](r, e, "service.content", false)
		}
	}
	return c, nil
}
func Snapshot(c Config) *configmodel.Document {
	d := &configmodel.Document{Version: 2, HasVersion: true}
	{
		s := &configmodel.Section{Name: "service"}
		s.Set("label", configmodel.Literal{Value: c.Service.Label})
		d.AddSection(s)
	}
	return d
}
func SetLiteral(c *Config, key, value string) error {
	switch key {
	case "service.label":
		c.Service.Label = value
	default:
		return fmt.Errorf("unknown configuration key %q", key)
	}
	return nil
}
