// Code generated by gogenconf. DO NOT EDIT.

package nativeconfig

// CommentKind records ownership rather than inferring it from prose.
type CommentKind uint8

const (
	UserComment CommentKind = iota
	DocumentationComment
)

// Item preserves ordered document structure. Adapters may add Raw items for
// syntax they intentionally do not interpret.
type Item interface{ item() }

type Comment struct {
	Kind CommentKind
	Text string
}

func (Comment) item() {}

type Blank struct{}

func (Blank) item() {}

type Entry struct {
	Key   string
	Value Expr
	// Defaulted is transient provenance for runtime precedence, never serialized.
	Defaulted bool
}

func (Entry) item() {}

type Raw struct{ Text string }

func (Raw) item() {}

type Section struct {
	Name  string
	Items []Item
}

func (*Section) item() {}

type Version struct{}

func (Version) item() {}

type Document struct {
	Version    int
	HasVersion bool
	Items      []Item
	Sections   []*Section
}

func (d *Document) Section(name string) *Section {
	for _, s := range d.Sections {
		if s.Name == name {
			return s
		}
	}
	return nil
}

func (s *Section) Entry(key string) (Entry, int, bool) {
	if s == nil {
		return Entry{}, -1, false
	}
	for i, item := range s.Items {
		if e, ok := item.(Entry); ok && e.Key == key {
			return e, i, true
		}
	}
	return Entry{}, -1, false
}

func (d *Document) AddSection(s *Section) {
	seen := map[*Section]bool{}
	for _, item := range d.Items {
		if section, ok := item.(*Section); ok {
			seen[section] = true
		}
	}
	for _, section := range d.Sections {
		if !seen[section] {
			d.Items = append(d.Items, section)
		}
	}
	d.Sections = append(d.Sections, s)
	d.Items = append(d.Items, s)
}

func (d *Document) Value(section, key string) Expr {
	e, _, ok := d.Section(section).Entry(key)
	if !ok {
		return nil
	}
	return e.Value
}

// Clone owns all slices and expression nodes, so migrations and providers do
// not share mutable declarations with the editing document.
func (d *Document) Clone() *Document {
	out := &Document{Version: d.Version, HasVersion: d.HasVersion}
	sections := map[*Section]*Section{}
	cloneItems := func(items []Item) []Item {
		result := make([]Item, 0, len(items))
		for _, item := range items {
			if e, ok := item.(Entry); ok {
				e.Value = CloneExpr(e.Value)
				item = e
			}
			result = append(result, item)
		}
		return result
	}
	for _, s := range d.Sections {
		c := &Section{Name: s.Name, Items: cloneItems(s.Items)}
		sections[s] = c
		out.Sections = append(out.Sections, c)
	}
	out.Items = cloneItems(d.Items)
	for i, item := range out.Items {
		if s, ok := item.(*Section); ok {
			out.Items[i] = sections[s]
		}
	}
	return out
}

func (s *Section) Set(key string, value Expr) {
	if _, i, ok := s.Entry(key); ok {
		s.Items[i] = Entry{Key: key, Value: value}
		return
	}
	s.Items = append(s.Items, Entry{Key: key, Value: value})
}

func (s *Section) Delete(key string) bool {
	if _, i, ok := s.Entry(key); ok {
		s.Items = append(s.Items[:i], s.Items[i+1:]...)
		return true
	}
	return false
}
