// Code generated by gogenconf. DO NOT EDIT.

package testfixture

import (
	"context"
	"fmt"
	gogenconf "github.com/arran4/gogenconf"
	"strings"
)

var _ = strings.Join
var _ = fmt.Errorf

type Config struct {
	Service ServiceConfig
}
type ServiceConfig struct {
	Label   string
	Key     []byte
	Content gogenconf.Provider[[]byte]
}

// Defaults returns concrete static defaults and optional legacy environment overrides.
func Defaults(lookup gogenconf.LookupEnv) Config {
	var c Config
	c.Service.Label = "default"
	if lookup != nil {
		if v, ok := lookup("FIXTURE_LABEL"); ok {
			c.Service.Label = v
		}
	}
	return c
}

// Resolve constructs ordinary Go fields; provider policy alone defers resolution.
func Resolve(ctx context.Context, d *gogenconf.Document, r *gogenconf.Registry, lookup gogenconf.LookupEnv) (Config, error) {
	var c Config
	if d == nil {
		return c, fmt.Errorf("nil document")
	}
	if d.Version > 2 {
		return c, fmt.Errorf("unsupported future configuration version")
	}
	{
		e := gogenconf.BindingValue(d, "service", "label", gogenconf.Literal{Value: "default"}, "FIXTURE_LABEL", false, lookup)
		if e == nil {
			return Config{}, fmt.Errorf("missing required field service.label")
		}
		if e != nil {
			value, err := gogenconf.ResolveField[string](ctx, r, e, "service.label", false)
			if err != nil {
				return Config{}, err
			}
			c.Service.Label = value
		}
	}
	{
		e := gogenconf.BindingValue(d, "service", "key", nil, "", false, lookup)
		if e == nil {
			return Config{}, fmt.Errorf("missing required field service.key")
		}
		if e != nil {
			value, err := gogenconf.ResolveField[[]byte](ctx, r, e, "service.key", true)
			if err != nil {
				return Config{}, err
			}
			c.Service.Key = value
		}
	}
	{
		e := gogenconf.BindingValue(d, "service", "content", nil, "", false, lookup)
		if e == nil {
			return Config{}, fmt.Errorf("missing required field service.content")
		}
		if e != nil {
			c.Service.Content = gogenconf.FieldProvider[[]byte](r, e, "service.content", false)
		}
	}
	return c, nil
}
